title: CMIP6
id: CMIP6_UofT
description: Coupled Model Intercomparison Project phase 6
keywords: ['CMIP', 'CMIP6', 'WCRP', 'Climate Change']
license: "CC-BY-4.0"
spatialextent: [-180, -90, 180, 90]
temporalextent: ['1850-01-01', '2500-01-01']

links:
    - rel: about
      title : Project homepage
      target : https://wcrp-cmip.org/cmip-phase-6-cmip6/
      media_type: text/html
    - rel: license
      title : License
      target : https://raw.githubusercontent.com/WCRP-CMIP/CMIP6_CVs/main/LICENSE-CC-BY
      media_type: text/plain
