title: HRDPS
id: HRDPS_CRIM
description: High Resolution Deterministic Prediction System
keywords:
  [
    "HRDPS",
    "ECCC",
    "MSC",
    "Climate Change",
    "Prediction",
    "High resolution",
    "Deterministic",
    "Meteorological data",
    "Weather and Climate",
    "Meteorological Service of Canada",
    "Environment and Climate Change Canada",
    "Weather and Environmental Operations",
  ]
license: other
spatialextent: [-152.7685268, 27.2840148, -40.6938032, 70.6164825]
temporalextent: ["2014-11-18", "2025-04-01"]

providers:
  - name: ECCC
    description: Environment and Climate Change Canada (ECCC)
    roles:
      - licensor
      - processor
      - producer
    url: https://github.com/julemai/CaSPAr/wiki/Available-products
  - name: MSC
    description: Meteorological Service of Canada (MSC)
    roles:
      - processor
    url: https://eccc-msc.github.io/open-data
  - name: Ouranos
    description: Ouranos
    roles:
      - processor
      - host
    url: https://www.ouranos.ca

links:
  - rel: about
    title : Project homepage
    target : https://open.canada.ca/data/en/dataset/5b401fa0-6c29-57f0-b3d5-749f301d829d
    media_type: text/html
    extra_fields:
      hreflang: en-CA
  - rel: about
    title : Page d'accueil du projet
    target : https://open.canada.ca/data/en/dataset/5b401fa0-6c29-57f0-b3d5-749f301d829d
    media_type: text/html
    extra_fields:
      hreflang: fr-CA
  - rel: author
    title: Environment and Climate Change Canada (ECCC)
    target: https://www.canada.ca/en/environment-climate-change.html
    media_type: text/html
    extra_fields:
      hreflang: en-CA
  - rel: author
    title: Environnement et Changement Climatique Canada (ECCC)
    target: https://www.canada.ca/fr/environnement-changement-climatique.html
    media_type: text/html
    extra_fields:
      hreflang: fr-CA
  - rel: describedby
    title: Data and Products of the High Resolution Deterministic Prediction System (HRDPS)
    target: https://eccc-msc.github.io/open-data/msc-data/nwp_hrdps/readme_hrdps_en
    media_type: text/html
    extra_fields:
      hreflang: en-CA
  - rel: describedby
    title: Données et Produits du Système à haute résolution de prévision déterministe (SHRPD)
    target: https://eccc-msc.github.io/open-data/msc-data/nwp_hrdps/readme_hrdps_fr
    media_type: text/html
    extra_fields:
      hreflang: fr-CA
  - rel: license
    title : Open Government Licence - Canada
    target : https://open.canada.ca/en/open-government-licence-canada
    media_type: text/html
    extra_fields:
      hreflang: en-CA
  - rel: license
    title: Licence du gouvernement ouvert – Canada
    target: https://ouvert.canada.ca/fr/licence-du-gouvernement-ouvert-canada
    media_type: text/html
    extra_fields:
      hreflang: fr-CA

contacts:
  - organization: Computer Research Institute of Montreal (CRIM)
    identifier: CRIM
    position: Support
    roles:
      - processor
    emails:
      - value: support-geo@crim.ca
        roles:
          - work
    logo:
      href: https://raw.githubusercontent.com/henriaidasso/image-store/refs/heads/main/img/crim.png
      rel: icon
      type: image/png
      title: CRIM
    links:
      - rel: about
        title: Site web
        target: https://www.crim.ca/fr/
        media_type: text/html
        extra_fields:
          hreflang: fr-CA
  - organization: Environment and Climate Change Canada (ECCC)
    identifier: ECCC
    position: Support
    roles:
      - licensor
      - processor
      - producer
    emails:
      - value: ECWeather-Meteo@ec.gc.ca
        roles:
          - work
    phones:
      - value: +18199972800
        roles:
          - work
    addresses:
      - deliveryPoint: 77 Westmorland Street, suite 260
        city: Fredericton
        administrativeArea: New Brunswick
        postalCode: E3B 6Z4
        country: Canada
    links:
      - rel: about
        title: Web page
        target: https://www.canada.ca/en/environment-climate-change.html
        media_type: text/html
        extra_fields:
          hreflang: en-CA
      - rel: about
        title: Site web
        target: https://www.canada.ca/fr/environnement-changement-climatique.html
        media_type: text/html
        extra_fields:
          hreflang: fr-CA
